### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by clmcavaney** [SimonButtazzi/node-red-contrib-boolean-parser#5]
Great node - love it - has enabled me to clean up flows big time.

Found a little typo:
"... cant't ..." should be "... can't ..."

https://github.com/SimonButtazzi/node-red-contrib-boolean-parser/blob/74bb7275df09ab78a724fcada7c283c81dee71c9/README.md?plain=1#L75

**Comment by SimonButtazzi** [comment]
Thanks, if you like it feel free to rate it: [https://flows.nodered.org/node/node-red-contrib-boolean-parser}
fixed within release 1.4.6
